# Generated by Django 5.0.6 on 2024-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
