# Generated by Django 4.2.13 on 2024-05-17 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_cart_created_at_cart_ordered_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 18, 26, 17, 121709)),
        ),
    ]
