# Generated by Django 4.2.13 on 2024-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_discount_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
