# Generated by Django 4.2.13 on 2024-05-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_cartitem_passenger_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'price', 'depart_date', 'return_date')},
        ),
    ]
