# Generated by Django 4.2.13 on 2024-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passaport',
            field=models.ImageField(blank=True, null=True, upload_to='passaports/'),
        ),
    ]
